"""Make type_id nullable

Revision ID: 28caf8fd5639
Revises: 45157d7dc8ce
Create Date: 2025-11-02 12:17:20.024619

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28caf8fd5639"
down_revision: Union[str, Sequence[str], None] = "45157d7dc8ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("packages", "type_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("packages", "type_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
