"""Update models

Revision ID: 45157d7dc8ce
Revises:
Create Date: 2025-10-31 17:47:19.727624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45157d7dc8ce"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_types",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("type_id", sa.UUID(), nullable=False),
        sa.Column(
            "contents_value_usd", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "delivery_cost_rub", sa.Numeric(precision=14, scale=2), nullable=True
        ),
        sa.Column("owner_session_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["type_id"], ["package_types.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_packages_owner_delivery",
        "packages",
        ["owner_session_id", "delivery_cost_rub"],
        unique=False,
    )
    op.create_index(
        op.f("ix_packages_owner_session_id"),
        "packages",
        ["owner_session_id"],
        unique=False,
    )
    op.create_index(
        "ix_packages_owner_type",
        "packages",
        ["owner_session_id", "type_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_packages_owner_type", table_name="packages")
    op.drop_index(op.f("ix_packages_owner_session_id"), table_name="packages")
    op.drop_index("ix_packages_owner_delivery", table_name="packages")
    op.drop_table("packages")
    op.drop_table("package_types")
    # ### end Alembic commands ###
